[versions]
android-tools-gradle = "8.9.3"
kotlin = "2.1.20"
ktor = "3.1.3"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
kotlinx-browser = "0.3"
androidx-test-core = "1.6.1"
roboelectric = "4.9"
opt-java = "1.3.2"
vault-client = "2.0.0"
versioning = "3.1.0"
npm-publishing = "3.5.3"
definitions = "5.124.0"

[libraries]
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin-legacy", version.ref = "ktor" }
ktor-client-jvm = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-browser = { group = "org.jetbrains.kotlinx", name = "kotlinx-browser", version.ref = "kotlinx-browser" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
roboelectric = { group = "org.robolectric", name = "robolectric", version.ref = "roboelectric" }
opt-java = { group = "com.github.bastiaanjansen", name = "otp-java", version.ref = "opt-java" }

[plugins]
vault-client = { id = "com.liftric.vault-client-plugin", version.ref = "vault-client" }
versioning = { id = "net.nemerosa.versioning", version.ref = "versioning" }
npm-publishing = { id = "dev.petuska.npm.publish", version.ref = "npm-publishing" }
definitions = { id = "io.github.turansky.kfc.definitions", version.ref = "definitions" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-tools-gradle" }